ECR_REPOSITORY_URL = "339713182449.dkr.ecr.ap-northeast-2.amazonaws.com/singsong-golang-private"
TARGET_GROUPS_URL = "/Users/sunwupark/Documents/SingSong-Infra/json/alb/alb-target-groups.json"
SECURITY_RULES_URL = "/Users/sunwupark/Documents/SingSong-Infra/json/alb/alb-security-rules.json"
CERTIFICATE_URL = "/Users/sunwupark/Documents/SingSong-Infra/json/certificate/certificate.crt"
PRIVATE_KEY_URL = "/Users/sunwupark/Documents/SingSong-Infra/json/certificate/private.key"
VPC_NAME = "singsong-vpc"
ECR_REPOSITORY_NAME = "singsong-golang-private"